import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CssBaseline from '@mui/joy/CssBaseline'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer/Footer'
import Sheet from '@mui/joy/Sheet'
import ProviderProvider from '@/components/Providers/ProviderProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>Dev Team Management</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body className={inter.className}>
        <ProviderProvider>
          <CssBaseline />
          <Sheet color='neutral'>
            <NavBar />
            {children}
            <Footer />
          </Sheet>
        </ProviderProvider>
      </body>
    </html>
  )
}
